name: rascal2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - llvm-openmp
  - openssl=3.6.2
  - expat=2.5.0
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
