name: Installer

on:
  push:
    branches: [ build_nightly ]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Windows-installer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
            activate-environment: rascal2
            environment-file: environment.yaml
            auto-activate-base: false
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
      - name: Make installer
        shell: powershell
        run: |
          conda init powershell
          conda activate rascal2
          conda install -c nsis nsis=3.* accesscontrol
          python packaging/build_exe.py
          makensis packaging/windows/build_installer.nsi
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: windows installer
          path: packaging/windows/*.exe
  Linux-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
      - name: Make installer
        shell: bash -l {0}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y makeself
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/hostedtoolcache/MATLAB/2023.1.999/x64/bin/glnxa64
          cd packaging/linux
          chmod 777 "build_installer.sh"
          mkdir build
          if [ ${{ github.ref_name }} == "master" ]; then
            ./build_installer.sh --remote
          else
            ./build_installer.sh --remote --tag $GITHUB_REF_NAME
          fi
          ./build_installer.sh --remote
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: linux installer
          path: packaging/linux/*.run
